projects:
  debug:
    enabled: false
    destination:
      name: "*"
      namespaces: ["*"]

  applications:
    enabled: false
    destination:
      name: "*"
      namespaces: ["*"]

  argocd:
    enabled: false
    destination:
      name: "*"
      namespaces: ["argocd"]

  prometheus:
    enabled: false
    destination:
      name: "*"
      namespaces: ["kube-system", "prometheus"]
    resourceWhitelist:
      - group: rbac.authorization.k8s.io
        kind: ClusterRole
      - group: rbac.authorization.k8s.io
        kind: ClusterRoleBinding
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
      - group: policy
        kind: PodSecurityPolicy

